# fly.toml app configuration file generated for srmacaback on 2024-01-24T21:24:48-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "srmacaback"
primary_region = "scl"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
